
image: Visual Studio 2017
configuration: AppVeyor
platform: Any CPU
skip_tags: true

matrix:
  fast_finish: true

environment:
  mdix_version: 2.5.1
  mdix_mahapps_version: 0.0.13
  mdix_colors_version: 1.1.4
  RestorePackages: false
  nuget_version: $(assembly_version)
  matrix:
    - assembly_version: $(mdix_version)
    - assembly_version: $(mdix_mahapps_version)
    - assembly_version: $(mdix_colors_version)

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(assembly_version).{build}'
  assembly_file_version: '$(assembly_version).{build}'
  assembly_informational_version: '$(assembly_version).{build}'

before_build:
- ps: .paket\paket.exe restore

build:
  project: MaterialDesignToolkit.Wpf.sln
  verbosity: minimal

after_build:
- ps: >-
    if ($env:assembly_version -eq $env:mdix_version) {
        7z a Demo.$($env:nuget_version).zip MainDemo.Wpf\bin\**\*.*
        nuget pack MaterialDesignThemes.nuspec -Version $env:nuget_version
    } elseif ($env:assembly_version -eq $env:mdix_mahapps_version) { 
        nuget pack MaterialDesignThemes.MahApps.nuspec -Version $env:nuget_version
    } elseif ($env:assembly_version -eq $env:mdix_colors_version) { 
        nuget pack MaterialDesignColors.nuspec -Version $env:nuget_version
    }

artifacts:
- path: '**\MaterialDesignThemes.*.nupkg'
- path: Demo.*.zip

for:
-
  branches:
    only:
      - master
  version: $(mdix_version)-ci{build}
  environment:
    nuget_version: $(assembly_version)-ci$(APPVEYOR_BUILD_NUMBER)
  deploy:
  - provider: NuGet
    api_key:
      secure: B+WIdbRYr/rJo1QMeDwNen2xcj4RTu1d8AZiA03kb8wsWZVQxt5OgsWRacmEjWRd
    artifact: MaterialDesignThemes.$(nuget_version).nupkg

-
  branches:
    only:
      - release
  version: $(mdix_version).{build}
